/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class products extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 234791172384032214L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"products\",\"fields\":[{\"name\":\"product_seris\",\"type\":\"string\"},{\"name\":\"product_name\",\"type\":\"string\"},{\"name\":\"prices\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"price\",\"fields\":[{\"name\":\"model\",\"type\":\"string\"},{\"name\":\"price\",\"type\":\"float\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<products> ENCODER =
      new BinaryMessageEncoder<products>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<products> DECODER =
      new BinaryMessageDecoder<products>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<products> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<products> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<products> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<products>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this products to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a products from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a products instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static products fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence product_seris;
   private java.lang.CharSequence product_name;
   private java.util.List<price> prices;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public products() {}

  /**
   * All-args constructor.
   * @param product_seris The new value for product_seris
   * @param product_name The new value for product_name
   * @param prices The new value for prices
   */
  public products(java.lang.CharSequence product_seris, java.lang.CharSequence product_name, java.util.List<price> prices) {
    this.product_seris = product_seris;
    this.product_name = product_name;
    this.prices = prices;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return product_seris;
    case 1: return product_name;
    case 2: return prices;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: product_seris = (java.lang.CharSequence)value$; break;
    case 1: product_name = (java.lang.CharSequence)value$; break;
    case 2: prices = (java.util.List<price>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'product_seris' field.
   * @return The value of the 'product_seris' field.
   */
  public java.lang.CharSequence getProductSeris() {
    return product_seris;
  }


  /**
   * Sets the value of the 'product_seris' field.
   * @param value the value to set.
   */
  public void setProductSeris(java.lang.CharSequence value) {
    this.product_seris = value;
  }

  /**
   * Gets the value of the 'product_name' field.
   * @return The value of the 'product_name' field.
   */
  public java.lang.CharSequence getProductName() {
    return product_name;
  }


  /**
   * Sets the value of the 'product_name' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.product_name = value;
  }

  /**
   * Gets the value of the 'prices' field.
   * @return The value of the 'prices' field.
   */
  public java.util.List<price> getPrices() {
    return prices;
  }


  /**
   * Sets the value of the 'prices' field.
   * @param value the value to set.
   */
  public void setPrices(java.util.List<price> value) {
    this.prices = value;
  }

  /**
   * Creates a new products RecordBuilder.
   * @return A new products RecordBuilder
   */
  public static products.Builder newBuilder() {
    return new products.Builder();
  }

  /**
   * Creates a new products RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new products RecordBuilder
   */
  public static products.Builder newBuilder(products.Builder other) {
    if (other == null) {
      return new products.Builder();
    } else {
      return new products.Builder(other);
    }
  }

  /**
   * Creates a new products RecordBuilder by copying an existing products instance.
   * @param other The existing instance to copy.
   * @return A new products RecordBuilder
   */
  public static products.Builder newBuilder(products other) {
    if (other == null) {
      return new products.Builder();
    } else {
      return new products.Builder(other);
    }
  }

  /**
   * RecordBuilder for products instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<products>
    implements org.apache.avro.data.RecordBuilder<products> {

    private java.lang.CharSequence product_seris;
    private java.lang.CharSequence product_name;
    private java.util.List<price> prices;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(products.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.product_seris)) {
        this.product_seris = data().deepCopy(fields()[0].schema(), other.product_seris);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.product_name)) {
        this.product_name = data().deepCopy(fields()[1].schema(), other.product_name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.prices)) {
        this.prices = data().deepCopy(fields()[2].schema(), other.prices);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing products instance
     * @param other The existing instance to copy.
     */
    private Builder(products other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.product_seris)) {
        this.product_seris = data().deepCopy(fields()[0].schema(), other.product_seris);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.product_name)) {
        this.product_name = data().deepCopy(fields()[1].schema(), other.product_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.prices)) {
        this.prices = data().deepCopy(fields()[2].schema(), other.prices);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'product_seris' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductSeris() {
      return product_seris;
    }


    /**
      * Sets the value of the 'product_seris' field.
      * @param value The value of 'product_seris'.
      * @return This builder.
      */
    public products.Builder setProductSeris(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.product_seris = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'product_seris' field has been set.
      * @return True if the 'product_seris' field has been set, false otherwise.
      */
    public boolean hasProductSeris() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'product_seris' field.
      * @return This builder.
      */
    public products.Builder clearProductSeris() {
      product_seris = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'product_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return product_name;
    }


    /**
      * Sets the value of the 'product_name' field.
      * @param value The value of 'product_name'.
      * @return This builder.
      */
    public products.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.product_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'product_name' field has been set.
      * @return True if the 'product_name' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'product_name' field.
      * @return This builder.
      */
    public products.Builder clearProductName() {
      product_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'prices' field.
      * @return The value.
      */
    public java.util.List<price> getPrices() {
      return prices;
    }


    /**
      * Sets the value of the 'prices' field.
      * @param value The value of 'prices'.
      * @return This builder.
      */
    public products.Builder setPrices(java.util.List<price> value) {
      validate(fields()[2], value);
      this.prices = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'prices' field has been set.
      * @return True if the 'prices' field has been set, false otherwise.
      */
    public boolean hasPrices() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'prices' field.
      * @return This builder.
      */
    public products.Builder clearPrices() {
      prices = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public products build() {
      try {
        products record = new products();
        record.product_seris = fieldSetFlags()[0] ? this.product_seris : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.product_name = fieldSetFlags()[1] ? this.product_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.prices = fieldSetFlags()[2] ? this.prices : (java.util.List<price>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<products>
    WRITER$ = (org.apache.avro.io.DatumWriter<products>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<products>
    READER$ = (org.apache.avro.io.DatumReader<products>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.product_seris);

    out.writeString(this.product_name);

    long size0 = this.prices.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (price e0: this.prices) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.product_seris = in.readString(this.product_seris instanceof Utf8 ? (Utf8)this.product_seris : null);

      this.product_name = in.readString(this.product_name instanceof Utf8 ? (Utf8)this.product_name : null);

      long size0 = in.readArrayStart();
      java.util.List<price> a0 = this.prices;
      if (a0 == null) {
        a0 = new SpecificData.Array<price>((int)size0, SCHEMA$.getField("prices").schema());
        this.prices = a0;
      } else a0.clear();
      SpecificData.Array<price> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<price>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          price e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new price();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.product_seris = in.readString(this.product_seris instanceof Utf8 ? (Utf8)this.product_seris : null);
          break;

        case 1:
          this.product_name = in.readString(this.product_name instanceof Utf8 ? (Utf8)this.product_name : null);
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<price> a0 = this.prices;
          if (a0 == null) {
            a0 = new SpecificData.Array<price>((int)size0, SCHEMA$.getField("prices").schema());
            this.prices = a0;
          } else a0.clear();
          SpecificData.Array<price> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<price>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              price e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new price();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










